spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root123456
    username: root
    url: jdbc:mysql://localhost:3306/spring_cloud?CharacterEncoding=utf8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
